CREATE TABLE Users (
CustomerId INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Username VARCHAR(40) NOT NULL,
Password VARCHAR(100) NOT NULL,
FirstName VARCHAR(30) NOT NULL,
LastName VARCHAR(30) NOT NULL,
Email VARCHAR(50) NOT NULL
);

CREATE TABLE 